apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  project: project
  source:
    repoURL: https://github.com/sonalmallah12/argo
    targetRevision: HEAD
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}

